---
# Service account for accessing secrets API
apiVersion: v1
kind: ServiceAccount
metadata:
 name: list-pods-service-account
 namespace: errbit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-get-pods
  namespace: errbit
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: add-list-get-pods-to-list-pods-sa
  namespace: errbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-get-pods
subjects:
- kind: ServiceAccount
  name: list-pods-service-account
  namespace: errbit
