apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongodb
spec:
  selector:
    matchLabels:
      role: mongodb
      environment: production
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        role: mongodb
        environment: production
    spec:
      serviceAccountName: list-pods-service-account
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
        - mongod
        - "--replSet"
        - rs0
        - "--smallfiles"
        - "--noprealloc"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongodb,environment=production"
          - name: KUBE_NAMESPACE
            value: errbit
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 20Gi
